apiVersion: v1
kind: Service
metadata:
  name: webz-ha
  labels:
    app: webz-ha
spec:
  type: {{ .Values.service.type }}
  selector:
    app: webz-ha
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
